---
galaxy_info:
  role_name: zram
  author: jweber
  description: Configure or disable zram swap
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Fedora
      versions:
        - all

dependencies: []
