---
- name: Destroy VM using foundry
  hosts: hypervisor
  become: true
  gather_facts: false
  tasks:
    - name: Fail if more than one host is targeted
      ansible.builtin.fail:
        msg: "You must limit the playbook to a single host using --limit"
      when: ansible_play_hosts | length != 1

    - name: Fail if vm_name is not defined or empty
      ansible.builtin.fail:
        msg: 'please pass an appropriate VM name with -e vm_name=<name>'
      when: vm_name is not defined or vm_name == ''

    - name: Destroy VM
      ansible.builtin.include_role:
        name: vm_destroy
      vars:
        vm_destroy_name: "{{ vm_name }}"
