---
galaxy_info:
  role_name: vm_create
  author: jweber
  description: Create VM using foundry CLI
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Fedora
      versions:
        - all

dependencies: []
