---
# Sushy-tools configuration
sushy_config_dir: /etc/sushy-tools
sushy_listen_ip: "{{ ansible_default_ipv4.address }}"
sushy_listen_port: 8000
sushy_libvirt_uri: "qemu:///system"
sushy_storage_pool: "foundry-vms"
